name: run main.py

on:
  schedule:
    - cron: "5 * * * *" # Every 12 hours
    

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Test secret
        run: |
          echo $TEST_SECRET
        env: 
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
