name: run main.py

on:
  schedule:
    - cron: '0 12 * * *' # Every 12 hours
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        env:
          SOME_SECRET: ${{ secrets.ACCESS_TOKEN }}
          run: python main.py
